<div class="mb-8">
    <div class="overlay mb-5">
        <div class="bgi-no-repeat bgi-position-center bgi-size-cover card-rounded">
            <img class="img-fluid rounded" src="{{ asset('images/news/news1.jpg') }}" alt="">
        </div>
    </div>
    <p href="#" class="text-dark text-justify fs-2 fw-bold">izidok Terus Berkembang Demi Mendukung Kebijakan Pemerintah Terkait Rekam Medis Elektronik</p>
</div>
<div class="fs-5 text-justify">
    <p>Mendukung integrasi dengan sistem pemerintah seperti BPJS dan Satu Sehat untuk mempermudah pekerjaan fasilitas pelayanan kesehatan.</p>
    <center><img width="750" class="img-fluid" src="{{ asset('images/demo/mockup_PIC-dashboard-izidok.png') }}" alt=""></center>
    <p class="text-center">Dasbor pemilik klinik yang bisa memantau aktivitas klinik dalam satu naungan manajemen.</p>
    <p>Sejak diterbitkannya Peraturan Kementerian Kesehatan No. 24 Tahun 2022 mengenai kewajiban menyelenggarakan rekam medis elektronik (RME), transformasi digital di bidang layanan kesehatan melaju pesat dilihat dari banyaknya penyedia layanan RME di Indonesia. Izidok sebagai salah satu penyedia layanan rekam medis elektronik yang sudah berkecimpung di industri ini sejak tahun 2020 turut serta dalam proses digitalisasi layanan kesehatan.</p>
    <p>Beragam fitur baru telah disiapkan izidok untuk mempermudah transisi fasilitas pelayanan kesehatan menjadi full digital. Berawal dari layanan RME untuk dokter, kini izidok mendukung sistem RME untuk klinik. Pemilik klinik kini dapat melakukan pengawasan terhadap beberapa klinik yang ia miliki melalui satu dashboard izidok. Selain itu terdapat fitur lain yang mendukung operasional fasilitas pelayanan kesehatan baik itu Dokter Praktik Mandiri maupun Klinik diantaranya fitur manajemen stok yang memudahkan dalam pengelolaan stok di fasyankes dimana pihak fasyankes dapat mengatur stok dan sistem akan otomatis mengurangi stok ketika dokter meresepkan obat ke pasien.</p>
    <p>Fitur lain yang tak kalah pentingnya adalah manajemen jasa medis, fitur ini dapat membantu mempermudah operasional fasyankes dalam melakukan perhitungan jasa medis secara otomatis kepada dokter dan staf pendukung layanan. Terdapat juga fitur pendukung lain yaitu izidok administratif yang menyediakan berbagai format surat yang biasa dibutuhkan fasyankes diantaranya surat persetujuan tindakan, surat keterangan sakit, dan resume medis. Modul farmasi dan resep digital turut memperkaya fitur izidok yang dapat meningkatkan mutu layanan kesehatan bagi fasyankes maupun pasien.</p>
    <center><img width="750" class="img-fluid" src="{{ asset('images/demo/mockup_satu-sehat.png') }}" alt=""></center>
    <p class="text-center">Pengaturan integrasi klinik dengan Satu Sehat</p>
    <h3>Aturan rekam medis elektronik</h3>
    <p>Layaknya perkembangan teknologi lainnya, pengembangan rekam medis elektronik juga diatur oleh pemerintah melalui Peraturan Menteri Kesehatan No. 24 Tahun 2022 dan detail implementasinya diatur dalam Keputusan Menteri Kesehatan HK.01.07/MENKES/1423/2022. Yang mana aturan ini menjadi pembaruan dari aturan yang menjadi acuan sebelumnya tentang rekam medis yaitu PMK No. 269/MENKES/PER/III/2008. Dalam PMK No. 24 Tahun 2022 disebutkan bahwa fasilitas pelayanan kesehatan wajib menyelenggarakan rekam medis elektronik maksimal 31 desember 2023.</p>
    <p>Saat ini pemerintah juga sedang menggalakkan integrasi sistem rekam medis elektronik dengan Satu Sehat yang merupakan platform milik kementerian kesehatan yang berfungsi sebagai sentralisasi data pasien dan terintegrasi dengan seluruh fasyankes di Indonesia sehingga memudahkan pembacaan informasi pasien saat terjadi perpindahan fasyankes. Saat ini layanan Rekam Medis Elektronik izidok telah terintegrasi dengan platform Satu Sehat milik Kemenkes.</p>
    <p>Untuk mendukung kemudahan aktivitas fasyankes dalam kegiatan operasional sehari-hari izidok juga telah terintegrasi dengan layanan PCare milik BPJS yang membantu proses klaim klinik pratama sehingga tidak perlu dua kali input, cukup input data konsultasi satu kali saja di izidok maka petugas tidak perlu lagi input ke dalam sistem Pcare. "Kepraktisan seperti inilah yang dibutuhkan oleh fasyankes di lapangan agar transisi dari manual ke digital dapat berjalan dengan lancar dan target digitalisasi sektor kesehatan Kemenkes di tahun 2025 dapat terwujud."</p>
    <center><img width="750" class="img-fluid" src="{{ asset('images/demo/mockup_registrasi-antrean-bpjs.png') }}" alt=""></center>
    <p class="text-center">Fitur pendaftaran antrian pasien yang telah terintegrasi dengan BPJS</p>
    <p>Selain integrasi dengan sistem pemerintah (BPJS dan Satu Sehat), Izidok juga mematuhi aturan pemerintah terkait sektor keamanan seperti standarisasi ISO 27001 dan terdaftar sebagai Penyelenggara Sistem Elektronik (PSE) Kominfo. Aturan mengenai standar penyimpanan rekam medis juga turut diimplementasi di izidok, setiap rekam medis akan disimpan selama 25 tahun sejak kunjungan terakhir pasien sebagai basis data acuan dokter dalam menentukan diagnosis pasien.</p>
    <h3>Rencana selanjutnya</h3>
    <p>Dalam pernyataannya, Alan Makagiansar selaku Chief Operating Officer menyatakan bahwa izidok akan terus melakukan pengembangan dan menambahkan fitur-fitur lain yang bisa membuat pelayanan kesehatan lebih baik lagi. Pengembangan izidok selanjutnya adalah iziDentist, aplikasi rekam medis elektronik yang dibuat khusus untuk mengakomodir kebutuhan dokter gigi. Berdasarkan informasi yang kami himpun dari beberapa dokter gigi, saat ini belum ada sistem rekam medis elektronik yang dibuat dengan standar rekam medis gigi dari kementerian kesehatan yang lengkap dengan odontogram beserta simbolnya yang mudah digunakan kapanpun dan dimanapun. Selain membawa seluruh keunggulan izidok, iziDentist akan menghadirkan fitur advanced odontogram yang sangat mudah dalam penggunaannya, dokter hanya perlu klik pada bagan gigi yang sedang sedang dikerjakan dan pilih keterangan yang telah disediakan. Selain itu, bagan ini akan berkelanjutan sehingga dokter tidak perlu mengulang pengisian dan dengan mudah memantau perkembangan kondisi gigi pasien di setiap kunjungannya. Dengan kemudahan ini diharapkan dokter gigi di seluruh Indonesia dapat lebih mudah dalam transisi ke rekam medis digital serta memudahkan operasional dokter gigi sehari-hari.</p>
    <p>Oleh sebab itu, izidok akan melakukan fundraising seri A untuk memenuhi kebutuhan pengembangan produk. Saat ini izidok sudah digunakan oleh ribuan dokter dan ratusan klinik yang tersebar di 38 provinsi di seluruh Indonesia. Kami akan fokus mengembangkan potensi wilayah yang sudah terdapat pengguna izidok agar dapat memaksimalkan penetrasi digitalisasi layanan rekam medis melalui success story pengguna izidok saat ini. Terdapat lebih dari 100.000 data pasien dan lebih dari 150.000 data rekam medis pasien dalam sistem izidok.</p>
    <p>Kami percaya izidok akan semakin berkembang karena selain digitalisasi sektor kesehatan saat ini merupakan sektor yang sedang menjadi sorotan karena sudah ada aturan pemerintah melalui PMK No. 24 Tahun 2022, kami juga memiliki visi one healthcare solution yang mengacu kepada digitalisasi industri kesehatan untuk Indonesia yang lebih baik.</p>
</div>