<div class="mb-8">
    <h1 href="#" class="text-dark text-center fw-bold">Menyambut 2024, Izidok Siap Menjadi Pionir Ekosistem Kesehatan Digital di Indonesia</h1>
</div>
<div class="fs-5 text-justify">
    <center><img width="750" class="img-fluid" src="{{ asset('images/news/izidok-menjadi-pionir.png') }}" alt=""></center>
    <p class="text-center fst-italic">Co-founding member izidok (M. Fauzi, Alan Makagiansar, Maulana)</p>
    <p>Perkembangan sistem pelayanan kesehatan di Indonesia saat ini sedang mengalami peningkatan yang cukup signifikan. Sistem yang sedang berjalan sudah berada di jalur yang tepat untuk mencapai pelayanan kesehatan universal. Mulai dari diselenggarakan program asuransi kesehatan wajib, yang dirancang agar masyarakat mendapatkan fasilitas kesehatan yang merata, hingga kebijakan transparansi di bidang kesehatan melalui digitalisasi di segala bidang kesehatan.</p>
    <p>Berkembangnya sistem pelayanan kesehatan saat ini bukan hanya ditujukan bagi masyarakat, melainkan memberikan keuntungan bagi fasyankes untuk mengembangkan layanan yang sesuai dengan Peraturan Menteri Kesehatan. Sebanyak 27.659 fasyankes di seluruh Indonesia telah diarahkan untuk beralih ke digital, pada 2024 mendatang.</p>
    <p>Berdasarkan Peraturan Menteri Kesehatan No.24 Tahun 2022, setiap fasilitas pelayanan kesehatan diwajibkan menggunakan rekam medis elektronik sebagai dokumen dalam pemberian pelayanan terhadap masyarakat. Keamanan dan kerahasiaan data menjadi salah satu aspek penting dalam implementasi sistem rekam medis elektronik.</p>
    <p>Sebagai salah satu penyedia sistem layanan kesehatan digital di Indonesia, Izidok mendukung penuh program digitalisasi layanan kesehatan. Terbukti dengan hadirnya sistem rekam medis elektronik berbasis web yang telah membantu lebih dari 6.000 Fasilitas Pelayanan Kesehatan (FASYANKES) yang tersebar di seluruh penjuru Indonesia dalam memberikan pelayanan kesehatan terbaik bagi masyarakat.</p>
    <p>Berawal dari sistem rekam medis elektronik untuk Dokter Praktik Mandiri, Izidok terus berinovasi dengan mengembangkan fitur untuk menunjang operasional klinik. Mulai dari integrasi data antar cabang, manajemen stok obat &amp; bahan habis pakai, surat penunjang pemeriksaan, manajemen komisi, pengingat konsultasi otomatis, hingga pembelian obat tanpa konsultasi untuk operasional Apotek. Hingga saat ini tercatat hampir 200.000 rekam medis serta 150.000 data pasien sudah tersimpan di dalam sistem izidok.</p>
    <p>Melihat kebutuhan dan peluang industri kesehatan di Indonesia, Izidok menghadirkan iziHealth yang siap menjadi pionir solusi ekosistem kesehatan digital, dengan menyediakan solusi untuk pasien, fasyankes, dan <em>stakeholder </em>lainnya di Industri kesehatan. Berbagai <em>usecase </em>telah disiapkan untuk menyambut ekosistem kesehatan digital. Di antaranya, aplikasi mobile yang berfungsi mulai dari reservasi dokter, akses resume medis hasil konsultasi, hingga asuransi pengguna.</p>
    <p>Fitur-fitur yang tersedia di aplikasi mobile dipersenjatai juga dengan teknologi Artificial Intelligence (AI) yang dapat membantu analisis data kondisi kesehatan pengguna serta merancang wellness activity dan pengecekan kesehatan.</p>
    <p>Bukan hanya itu, Izidok juga menawarkan solusi Business-to-Business (B2B), berupa solusi middleware yang menjawab kebutuhan Fasilitas Pelayanan Kesehatan (FASYANKES) agar bisa terhubung dengan Satu Sehat dan BPJS. Alan Makagiansar selaku Chief Operating Officer izidok menyampaikan usai Rapat Kerja 2024 bahwa "Berbagai kemudahan dari seluruh aspek kesehatan dapat ditemukan di iziHealth, mulai dari aplikasi untuk pasien, pelayanan kesehatan, asuransi, hingga farmasi. Bersama iziHealth kami siap mendigitalisasi sektor kesehatan di Indonesia."</p>
</div>